// Package svcgen turns abstract service definitions into init-system files.
//
// Recipes never write unit files. They declare what a service is — what to
// run, and what must be running first — and both a systemd unit and an s6-rc
// definition are generated from that.
//
// The reason is the minimal profile, which runs busybox and s6 rather than
// systemd on boards too small for it. If recipes shipped unit files, every
// recipe that starts a daemon would need a second hand-written copy, they
// would drift, and the small-board tier would quietly rot. Generating both
// from one declaration means a recipe author cannot forget the tier they do
// not personally use.
package svcgen

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// Service is the abstract declaration, mirroring the recipe stanza.
type Service struct {
	Name    string
	Exec    string
	After   []string
	Wants   []string
	Restart string // "" (default: on-failure), "always", "never"

	// Verbose says this service's output belongs in a log file rather than on
	// the console.
	//
	// It exists because of one measurement: a datapath daemon carrying a
	// vendor SDK writes tens of thousands of initialisation lines, and on a
	// switch reached over a 9600 baud serial console that turns a few seconds
	// of chip setup into ten minutes of unusable console. The output is worth
	// keeping and is not worth watching.
	Verbose bool
}

// File is one generated file to install.
type File struct {
	Path    string
	Mode    uint32
	Content string
}

// Backend generates files for one init system.
type Backend interface {
	// ID is the init system's name, as used in a profile.
	ID() string
	Generate(s Service) ([]File, error)
}

// For returns the backend for an init system.
func For(init string) (Backend, error) {
	switch init {
	case "systemd":
		return systemd{}, nil
	case "s6":
		return s6{}, nil
	default:
		return nil, fmt.Errorf("svcgen: unknown init system %q (known: systemd, s6)", init)
	}
}

// All returns every backend. Packages generate for all of them, because a
// package is built once and may be composed into images of any profile.
func All() []Backend { return []Backend{systemd{}, s6{}} }

// Validate rejects a declaration that cannot be expressed in every backend,
// so the failure lands on the recipe author rather than on whoever first
// builds a minimal image months later.
func (s Service) Validate() error {
	if s.Name == "" {
		return fmt.Errorf("service name is required")
	}
	if strings.ContainsAny(s.Name, " \t/\n") {
		return fmt.Errorf("service name %q may not contain spaces, slashes or newlines", s.Name)
	}
	if s.Exec == "" {
		return fmt.Errorf("service %q: exec is required", s.Name)
	}
	if strings.ContainsAny(s.Exec, "\n\r") {
		return fmt.Errorf("service %q: exec may not contain newlines", s.Name)
	}
	if !path.IsAbs(strings.Fields(s.Exec)[0]) {
		return fmt.Errorf("service %q: exec must start with an absolute path, got %q",
			s.Name, strings.Fields(s.Exec)[0])
	}
	// Single quotes do not group in execline.
	//
	// The s6 backend renders exec into an execline script, and execline groups
	// on DOUBLE quotes only -- a single-quoted region is split on whitespace
	// like anything else. So
	//
	//     /bin/sh -c 'A=1; echo $A'
	//
	// reaches sh as the single argument "'A=1;" and the rest becomes arguments
	// to sh itself. It is accepted, it runs, and it does something entirely
	// different from what was written, which is how one of these silently
	// failed to bind a PCI device and blocked every service that depended on
	// it. systemd would have parsed the same line correctly, so it works on one
	// tier and not the other.
	//
	// Refused rather than rewritten: quoting that has to be guessed at is worth
	// a build failure, and anything needing real shell grammar wants a script
	// file rather than an exec line.
	if strings.Contains(s.Exec, "'") {
		return fmt.Errorf("service %q: exec may not contain single quotes -- they do "+
			"not group in execline, so the command would be split into words. Use "+
			"double quotes, or put it in a script and exec that", s.Name)
	}
	switch s.Restart {
	case "", "on-failure", "always", "never":
	default:
		return fmt.Errorf("service %q: restart %q must be one of on-failure, always, never",
			s.Name, s.Restart)
	}
	return nil
}

func sorted(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------- systemd

type systemd struct{}

func (systemd) ID() string { return "systemd" }

func (systemd) Generate(s Service) ([]File, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# Generated by nosaic from the recipe's services: stanza.\n")
	b.WriteString("# Do not edit: regenerate the package instead.\n\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", s.Name)
	if len(s.After) > 0 {
		fmt.Fprintf(&b, "After=%s\n", strings.Join(unitNames(sorted(s.After)), " "))
	}
	if len(s.Wants) > 0 {
		fmt.Fprintf(&b, "Wants=%s\n", strings.Join(unitNames(sorted(s.Wants)), " "))
	}
	b.WriteString("\n[Service]\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", s.Exec)
	switch s.Restart {
	case "never":
		b.WriteString("Restart=no\n")
	case "always":
		b.WriteString("Restart=always\nRestartSec=5\n")
	default:
		b.WriteString("Restart=on-failure\nRestartSec=5\n")
	}
	b.WriteString("\n[Install]\nWantedBy=multi-user.target\n")

	return []File{{
		Path:    "/usr/lib/systemd/system/" + s.Name + ".service",
		Mode:    0o644,
		Content: b.String(),
	}}, nil
}

// unitNames appends .service to bare names. "network" and other well-known
// targets are left alone.
func unitNames(in []string) []string {
	out := make([]string, len(in))
	for i, n := range in {
		switch {
		case strings.Contains(n, "."):
			out[i] = n // already qualified: foo.service, network.target
		case n == "network" || n == "basic" || n == "sysinit" || n == "multi-user":
			out[i] = n + ".target"
		default:
			out[i] = n + ".service"
		}
	}
	return out
}

// --------------------------------------------------------------------- s6

type s6 struct{}

func (s6) ID() string { return "s6" }

func (s6) Generate(s Service) ([]File, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	dir := "/etc/s6-rc/source/" + s.Name

	// A service that must not restart is a oneshot, not a longrun with a
	// signal attached. s6-rc supervises a longrun and starts it again every
	// time it exits, which for something that configures the box and returns
	// means it runs forever.
	//
	// That is not theoretical: the network configuration service was generated
	// as a longrun and respawned in a loop on the first switch it ran on,
	// flooding the console it was reporting to.
	//
	// A oneshot is described by an up script rather than a run script, and
	// s6-rc reads it with execline, so it is a command line rather than a
	// shell script with a shebang.
	var files []File
	if s.Restart == "never" {
		files = []File{
			{Path: dir + "/type", Mode: 0o644, Content: "oneshot\n"},
			{
				Path: dir + "/up",
				Mode: 0o644,
				// redirfd and fdmove send its output to the same place a
				// longrun's would go, so a oneshot is not silently quieter
				// than the service beside it.
				Content: oneshotLine(s),
			},
		}
	} else {
		files = []File{
			{Path: dir + "/type", Mode: 0o644, Content: "longrun\n"},
			{
				Path: dir + "/run",
				Mode: 0o755,
				Content: "#!/bin/sh\n" +
					"# Generated by nosaic from the recipe's services: stanza.\n" +
					"# Do not edit: regenerate the package instead.\n" +
					"exec 2>&1\n" +
					logRedirect(s) +
					"exec " + s.Exec + "\n",
			},
		}
		// A pause after a failed run, as systemd's RestartSec=5 gives the
		// other tier. s6-supervise waits only about a second between starts,
		// so a service that cannot start spins; s6 kills a finish script
		// after 5 s, hence 4.
		files = append(files, File{
			Path: dir + "/finish",
			Mode: 0o755,
			Content: "#!/bin/sh\n" +
				"# Generated by nosaic. Back off after a failed run.\n" +
				"[ \"$1\" = 0 ] || sleep 4\n",
		})
		if s.Verbose {
			files = append(files, logger(s)...)
		}
	}

	// s6-rc expresses ordering with an empty file per dependency. systemd's
	// After and Wants collapse to the same thing here, because s6-rc has one
	// notion of dependency rather than separate ordering and wanting.
	deps := map[string]bool{}
	for _, d := range append(append([]string(nil), s.After...), s.Wants...) {
		deps[bareName(d)] = true
	}
	names := make([]string, 0, len(deps))
	for d := range deps {
		names = append(names, d)
	}
	for _, d := range sorted(names) {
		files = append(files, File{
			Path: dir + "/dependencies.d/" + d, Mode: 0o644, Content: "",
		})
	}

	return files, nil
}

// bareName strips a systemd-style suffix, since s6 dependency names have none.
func bareName(n string) string {
	for _, suf := range []string{".service", ".target", ".socket"} {
		if strings.HasSuffix(n, suf) {
			return strings.TrimSuffix(n, suf)
		}
	}
	return n
}

// logger builds the companion service that captures a verbose longrun's output.
//
// s6-rc wires a producer to its consumer with a pipe and supervises each half
// separately, which is what makes this safe: the daemon keeps its own process
// and its own signals, so a stop still reaches it. Piping inside the run script
// would put a shell between s6 and the daemon, and s6's SIGTERM would go to the
// shell -- which does not forward it -- so a graceful stop would stop being
// graceful, and this fleet depends on that (killing a datapath daemon leaves
// the chip needing a board reset).
//
// The size cap is the point. A plain file grows until the filesystem is gone,
// and on a board that RAM-boots the filesystem is RAM: a datapath daemon on the
// 7050SX2 wrote 2 GB into /var/log/nosd.log at 176 KB/s and filled all of
// /mnt/data, after which writes to /etc returned I/O errors and the box was
// slow in ways that looked like anything but logging. Filtering what the SDK
// emits fixed the rate; only a bound fixes the failure.
//
// Three files of 1 MB: enough to see an initialisation sequence and a fault
// after it, and small enough that the worst case is 3 MB on a board with 2 GB.
func logger(s Service) []File {
	name := bareName(s.Name)
	dir := "/etc/s6-rc/source/" + name + "-log"

	return []File{
		{Path: "/etc/s6-rc/source/" + name + "/producer-for", Mode: 0o644,
			Content: name + "-log\n"},
		{Path: dir + "/type", Mode: 0o644, Content: "longrun\n"},
		{Path: dir + "/consumer-for", Mode: 0o644, Content: name + "\n"},
		{Path: dir + "/run", Mode: 0o755,
			Content: "#!/bin/sh\n" +
				"# Generated by nosaic from the recipe's services: stanza.\n" +
				"# Do not edit: regenerate the package instead.\n" +
				"mkdir -p /var/log/" + name + "\n" +
				"exec s6-log -b n3 s1000000 /var/log/" + name + "\n"},
	}
}

// logRedirect sends a verbose service's output to a file instead of the
// console, which is where a longrun's output otherwise lands.
//
// A plain file rather than a logging chain: this has to work on the minimal
// profile, where there is no syslog and the point of the tier is that there is
// very little of anything. Truncated at each start so a restarting service
// cannot fill the filesystem it is running on.
func logRedirect(s Service) string {
	if !s.Verbose {
		return ""
	}
	path := "/var/log/" + bareName(s.Name)

	// Nothing to redirect for a longrun any more: s6-rc has already made this
	// service's stdout the pipe into its logger, and redirecting to a file
	// would send the output somewhere the size cap does not apply.
	//
	// ⚠ ONCE PER BOOT, NOT PER START. A longrun that fails is restarted
	// every second or so, and a breadcrumb per start is a console flood:
	// the S6000 rehearsal's thermal service, with no board controller under
	// QEMU, buried the console so deeply that commands typed at it were
	// lost -- which is exactly the state a console is looked at in.
	if s.Restart != "never" {
		mark := "/run/nosaic-said-" + bareName(s.Name)
		return "[ -e " + mark + " ] || { echo '" + bareName(s.Name) + ": output to " + path +
			"/current' >/dev/console 2>/dev/null; : >" + mark + "; } 2>/dev/null || true\n"
	}

	// One line to the console saying where the rest went.
	//
	// Without it a verbose service is indistinguishable on the console from
	// one that never started, and the console is exactly where someone looks
	// when a board will not come up. That cost real time on the AS5610: nosd
	// was crash-looping and the console showed nothing at all, which reads as
	// "the service is missing" rather than "the service is failing loudly
	// somewhere else".
	//
	// Redirected to the console explicitly rather than just printed, because
	// this runs after `exec 2>&1` and has to escape the redirect that is about
	// to be installed on the next line. Failure is ignored: a board with no
	// /dev/console should not lose its datapath over a breadcrumb.
	return "echo '" + bareName(s.Name) + ": output to " + path +
		"' >/dev/console 2>/dev/null || true\n" +
		"mkdir -p /var/log\n" +
		"exec >" + path + " 2>&1\n"
}

func oneshotLine(s Service) string {
	if s.Verbose {
		path := "/var/log/" + bareName(s.Name) + ".log"
		// ⚠ MAKE THE DIRECTORY FIRST. redirfd cannot create one, so on a board
		// where nothing else has made /var/log yet this redirection fails, the
		// oneshot fails with it, and `s6-rc change` returns non-zero -- which
		// this init treats as "the service database did not come up" and
		// answers with a rescue shell. A verbose oneshot could therefore cost
		// the whole boot: no network, no datapath, and an unauthenticated
		// shell reading the console. The longrun path above already does this;
		// this one did not.
		return "foreground { mkdir -p /var/log } " +
			"redirfd -w 1 " + path + " fdmove -c 2 1 " + s.Exec + "\n"
	}
	// redirfd and fdmove send its output to the same place a longrun's would
	// go, so a oneshot is not silently quieter than the service beside it.
	return "redirfd -w 2 /dev/console fdmove -c 1 2 " + s.Exec + "\n"
}
