#!/bin/sh
# Generate this board's per-port datapath tables from a SONiC config.bcm.
#
# WHY THIS EXISTS
#
# Which SerDes lane each front-panel cage uses, which differential pairs the
# PCB inverted, and the transmit equalisation each trace needs are facts about
# this board's copper. Dell published them for SONiC in the board's
# config.bcm; they are vendor-derived, so NOSaic ships this generator and not
# its output.
#
# They describe the board, not the unit, so any S6000 config.bcm will do:
#
#   - from a switch running SONiC:
#       /usr/share/sonic/hwsku/td2-s6000-32x40G.config.bcm
#   - from sonic-buildimage (branch 202012 or later):
#       device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/td2-s6000-32x40G.config.bcm
#
# SONiC's file is already key=value, the format the datapath reads, so this
# only sorts it into the three files nosd-td2 loads and renames one family of
# keys.
#
# WHAT IT WRITES
#
#   portmap.conf    portmap_N           logical port -> first physical lane:speed
#   polarity.conf   xgxs_{rx,tx}_lane_map_N, phy_xaui_{rx,tx}_polarity_flip_N
#   serdes.conf     serdes_{preemphasis,driver_current,pre_driver_current}_laneK_N
#
# ⚠ SONiC NAMES THE SERDES KEYS BY SDK PORT NAME, NOT BY LOGICAL PORT.
#
# In the 32x40G file they end _xe0.._xe31, the names the SDK gives xe ports in
# logical-port order. That is logical port 1..32 on this map, but only by
# coincidence of numbering: the Q24S32 SKU, which breaks cages out, keys the
# same values by logical number instead. They are rewritten to logical numbers
# here -- xeK is the K-th logical port that has a portmap entry -- so the
# three files agree with each other whatever map they came from.
#
# ⚠ ONLY 40G. SONiC numbers the 32 cages 1..32 consecutively, and the
# datapath's portmode breakout needs each 40G port's next three logical
# numbers free. Breakout is a renumbering, not a flag, and is not done here.
#
# ⚠ THE BIT-15 TAP-FORCE CAVEAT DOES NOT NEED HANDLING HERE: every
# serdes_preemphasis value in Dell's file already has bit 15 set (0xa370 ..
# 0xd2b0). The check below refuses one that does not, rather than silently
# producing a port that ignores its main and post taps.
#
# USAGE
#   ./mkconf.sh <config.bcm> <output-dir>
#
# then put the three files where the datapath looks: /mnt/data/config on an
# installed switch, or platform/dell-s6000-on/config/ before `make image` or
# `make netboot` (a RAM boot has no /mnt/data to keep them in). Never commit
# them.
set -eu

if [ $# -ne 2 ]; then
    echo "usage: $0 <config.bcm> <output-dir>" >&2
    exit 2
fi
IN=$1
OUT=$2
[ -r "$IN" ] || { echo "error: cannot read $IN" >&2; exit 1; }
mkdir -p "$OUT"

# Strip comments and whitespace; keep only key=value lines.
clean() {
    sed -e 's/#.*//' -e 's/[[:space:]]//g' "$IN" | grep -E '^[A-Za-z0-9_.]+=.+$' || true
}

HEADER="# Generated by platform/dell-s6000-on/tools/mkconf.sh from
#   $(basename "$IN")
# Vendor-derived per-port data. Do not commit."

clean | grep -E '^portmap_[0-9]+=' | sort -t_ -k2 -n > "$OUT/.portmap.tmp"
if [ ! -s "$OUT/.portmap.tmp" ]; then
    rm -f "$OUT/.portmap.tmp"
    echo "error: no portmap_N lines in $IN; is this a config.bcm?" >&2
    exit 1
fi
if grep -qv ':40$' "$OUT/.portmap.tmp"; then
    rm -f "$OUT/.portmap.tmp"
    echo "error: $IN maps ports at speeds other than 40G; only the 32x40G map is supported" >&2
    exit 1
fi
{ echo "$HEADER"; cat "$OUT/.portmap.tmp"; } > "$OUT/portmap.conf"

clean | grep -E '^(xgxs_(rx|tx)_lane_map|phy_xaui_(rx|tx)_polarity_flip)_[0-9]+=' \
    | sort > "$OUT/.polarity.tmp"
{ echo "$HEADER"; cat "$OUT/.polarity.tmp"; } > "$OUT/polarity.conf"

# serdes: _xeK -> _<K-th logical port>, _<N> kept as is.
clean | grep -E '^serdes_(preemphasis|driver_current|pre_driver_current)_lane[0-3]_(xe[0-9]+|[0-9]+)=' \
    | awk -F'[=]' -v map="$OUT/.portmap.tmp" '
    # Portable hex parse: strtonum() and and() are GNU awk only.
    function hex(s,    i, c, v) {
        s = tolower(s); sub(/^0x/, "", s); v = 0
        for (i = 1; i <= length(s); i++) {
            c = index("0123456789abcdef", substr(s, i, 1))
            if (c == 0) return -1
            v = v * 16 + c - 1
        }
        return v
    }
    BEGIN {
        n = 0
        while ((getline line < map) > 0) {
            split(line, kv, "=")
            sub(/^portmap_/, "", kv[1])
            logical[n++] = kv[1]
        }
    }
    {
        key = $1; val = $2
        if (match(key, /_xe[0-9]+$/)) {
            k = substr(key, RSTART + 3) + 0
            if (!(k in logical)) {
                printf "error: %s names xe%d but the map has only %d ports\n", key, k, n > "/dev/stderr"
                bad = 1; next
            }
            key = substr(key, 1, RSTART) logical[k]
        }
        if (key ~ /^serdes_preemphasis_/ && int(hex(val) / 32768) % 2 == 0) {
            printf "error: %s=%s lacks the tap-force bit 0x8000\n", key, val > "/dev/stderr"
            bad = 1; next
        }
        print key "=" val
    }
    END { exit bad }' > "$OUT/.serdes.raw" || {
        # Not through a pipe into sort: that would report sort's status and
        # write a half-empty serdes.conf beside a refusal nobody reads.
        rm -f "$OUT"/.*.tmp "$OUT/.serdes.raw" "$OUT/portmap.conf" "$OUT/polarity.conf"
        echo "error: refused; nothing written" >&2
        exit 1
    }
sort "$OUT/.serdes.raw" > "$OUT/.serdes.tmp"
rm -f "$OUT/.serdes.raw"
{ echo "$HEADER"; cat "$OUT/.serdes.tmp"; } > "$OUT/serdes.conf"

ports=$(grep -c . "$OUT/.portmap.tmp")
pol=$(grep -c . "$OUT/.polarity.tmp" || true)
ser=$(grep -c . "$OUT/.serdes.tmp" || true)
rm -f "$OUT/.portmap.tmp" "$OUT/.polarity.tmp" "$OUT/.serdes.tmp"
echo "wrote $OUT/portmap.conf ($ports ports), polarity.conf ($pol lines), serdes.conf ($ser lines)" >&2
