#!/bin/sh
# Generate this board's per-port datapath tables from a SONiC config.bcm.
#
# WHY THIS EXISTS
#
# Which SerDes lane each front-panel cage uses, which differential pairs the
# PCB inverted, and the transmit equalisation each trace needs are facts about
# this board's copper. Dell published them for SONiC in the board's
# config.bcm; they are vendor-derived, so NOSaic ships this generator and not
# its output.
#
# They describe the board, not the unit, so any S6000 config.bcm will do:
#
#   - from a switch running SONiC:
#       /usr/share/sonic/hwsku/td2-s6000-32x40G.config.bcm
#   - from sonic-buildimage (branch 202012 or later):
#       device/dell/x86_64-dell_s6000_s1220-r0/Force10-S6000/td2-s6000-32x40G.config.bcm
#
# SONiC's file is already key=value, the format the datapath reads, so this
# only sorts it into the three files nosd-td2 loads and renames one family of
# keys.
#
# WHAT IT WRITES
#
#   portmap.conf    portmap_N           logical port -> first physical lane:speed
#   polarity.conf   xgxs_{rx,tx}_lane_map_N, phy_xaui_{rx,tx}_polarity_flip_N
#   serdes.conf     serdes_{preemphasis,driver_current,pre_driver_current}_laneK_N
#
# ⚠ SONiC NAMES THE SERDES KEYS BY SDK PORT NAME, NOT BY LOGICAL PORT.
#
# In the 32x40G file they end _xe0.._xe31, the names the SDK gives xe ports in
# logical-port order. That is logical port 1..32 on this map, but only by
# coincidence of numbering: the Q24S32 SKU, which breaks cages out, keys the
# same values by logical number instead. They are rewritten to logical numbers
# here -- xeK is the K-th logical port that has a portmap entry -- so the
# three files agree with each other whatever map they came from.
#
# ⚠ ONLY 40G. SONiC numbers the 32 cages 1..32 consecutively, and the
# datapath's portmode breakout needs each 40G port's next three logical
# numbers free. Breakout is a renumbering, not a flag, and is not done here.
#
# ⚠ THE BIT-15 TAP-FORCE CAVEAT DOES NOT NEED HANDLING HERE: every
# serdes_preemphasis value in Dell's file already has bit 15 set (0xa370 ..
# 0xd2b0). The check below refuses one that does not, rather than silently
# producing a port that ignores its main and post taps.
#
# 4x10G BREAKOUT: --breakout <cage,cage,...>
#
# Cages are numbered 1-32 in front-panel order (cage N is SONiC's
# fortyGigE0/<4(N-1)>). A listed cage is given four logical port numbers
# instead of one, the rest renumbered after it, and the datapath's portmode
# mechanism splits it into four 10G ports at boot (portmode.conf,
# nosaic_portmode_<base>=4x10g). The per-lane data follows Dell's own
# breakout configs, checked against the Q24S32 SKU for the same cage:
#
#   lane 1 keeps the 40G port's keys unchanged -- lane maps, the 4-bit
#     polarity masks and all four lanes' serdes values;
#   lanes 2-4 get only polarity: bit <i> of the 40G port's mask.
#
# Interface names come out with the map, in portmap.conf, because the logical
# numbers now depend on the layout: et<cage> for a 40G cage, et<cage>_1 ..
# et<cage>_4 for a broken-out one, each on internal VLAN 1000+<logical>.
#
# Switching a cage between 40G and 4x10G is re-running this with a different
# list and restarting nosd. The Trident II's limits are checked: at most 52
# front-panel ports per pipeline (cages 1-16 and 17-32), and NOSaic's 64
# Linux interfaces.
#
# USAGE
#   ./mkconf.sh <config.bcm> <output-dir> [--breakout 29,30]
#
# then put the four files where the datapath looks: /mnt/data/config on an
# installed switch, or platform/dell-s6000-on/config/ before `make image` or
# `make netboot` (a RAM boot has no /mnt/data to keep them in). Never commit
# them.
set -eu

BREAKOUT=""
if [ $# -eq 4 ] && [ "$3" = --breakout ]; then
    BREAKOUT=$4
elif [ $# -ne 2 ]; then
    echo "usage: $0 <config.bcm> <output-dir> [--breakout <cage,...>]" >&2
    exit 2
fi
IN=$1
OUT=$2
case "$BREAKOUT" in
    *[!0-9,]*) echo "error: --breakout takes cage numbers 1-32, e.g. 29,30" >&2; exit 2 ;;
esac
[ -r "$IN" ] || { echo "error: cannot read $IN" >&2; exit 1; }
mkdir -p "$OUT"

# Strip comments and whitespace; keep only key=value lines.
clean() {
    sed -e 's/#.*//' -e 's/[[:space:]]//g' "$IN" | grep -E '^[A-Za-z0-9_.]+=.+$' || true
}

HEADER="# Generated by platform/dell-s6000-on/tools/mkconf.sh from
#   $(basename "$IN")
# Vendor-derived per-port data. Do not commit."

clean | grep -E '^portmap_[0-9]+=' | sort -t_ -k2 -n > "$OUT/.portmap.tmp"
if [ ! -s "$OUT/.portmap.tmp" ]; then
    rm -f "$OUT/.portmap.tmp"
    echo "error: no portmap_N lines in $IN; is this a config.bcm?" >&2
    exit 1
fi
if grep -qv ':40$' "$OUT/.portmap.tmp"; then
    rm -f "$OUT/.portmap.tmp"
    echo "error: $IN maps ports at speeds other than 40G; only the 32x40G map is supported" >&2
    exit 1
fi
{ echo "$HEADER"; cat "$OUT/.portmap.tmp"; } > "$OUT/portmap.conf"

clean | grep -E '^(xgxs_(rx|tx)_lane_map|phy_xaui_(rx|tx)_polarity_flip)_[0-9]+=' \
    | sort > "$OUT/.polarity.tmp"
{ echo "$HEADER"; cat "$OUT/.polarity.tmp"; } > "$OUT/polarity.conf"

# serdes: _xeK -> _<K-th logical port>, _<N> kept as is.
clean | grep -E '^serdes_(preemphasis|driver_current|pre_driver_current)_lane[0-3]_(xe[0-9]+|[0-9]+)=' \
    | awk -F'[=]' -v map="$OUT/.portmap.tmp" '
    # Portable hex parse: strtonum() and and() are GNU awk only.
    function hex(s,    i, c, v) {
        s = tolower(s); sub(/^0x/, "", s); v = 0
        for (i = 1; i <= length(s); i++) {
            c = index("0123456789abcdef", substr(s, i, 1))
            if (c == 0) return -1
            v = v * 16 + c - 1
        }
        return v
    }
    BEGIN {
        n = 0
        while ((getline line < map) > 0) {
            split(line, kv, "=")
            sub(/^portmap_/, "", kv[1])
            logical[n++] = kv[1]
        }
    }
    {
        key = $1; val = $2
        if (match(key, /_xe[0-9]+$/)) {
            k = substr(key, RSTART + 3) + 0
            if (!(k in logical)) {
                printf "error: %s names xe%d but the map has only %d ports\n", key, k, n > "/dev/stderr"
                bad = 1; next
            }
            key = substr(key, 1, RSTART) logical[k]
        }
        if (key ~ /^serdes_preemphasis_/ && int(hex(val) / 32768) % 2 == 0) {
            printf "error: %s=%s lacks the tap-force bit 0x8000\n", key, val > "/dev/stderr"
            bad = 1; next
        }
        print key "=" val
    }
    END { exit bad }' > "$OUT/.serdes.raw" || {
        # Not through a pipe into sort: that would report sort's status and
        # write a half-empty serdes.conf beside a refusal nobody reads.
        rm -f "$OUT"/.*.tmp "$OUT/.serdes.raw" "$OUT/portmap.conf" "$OUT/polarity.conf"
        echo "error: refused; nothing written" >&2
        exit 1
    }
sort "$OUT/.serdes.raw" > "$OUT/.serdes.tmp"
rm -f "$OUT/.serdes.raw"
{ echo "$HEADER"; cat "$OUT/.serdes.tmp"; } > "$OUT/serdes.conf"

# ── Layout: cage -> logical port, with room for the broken-out cages ─────────
#
# Up to here every key is numbered by Dell's 32x40G map, where logical port N
# is front-panel cage N. Renumber them all for the chosen layout, and add what
# a broken-out cage needs.
cat "$OUT/.portmap.tmp" "$OUT/.polarity.tmp" "$OUT/.serdes.tmp" | awk -F= \
    -v breakout="$BREAKOUT" -v hdr="$HEADER" -v out="$OUT" '
function die(m) { print "error: " m > "/dev/stderr"; bad = 1; exit 1 }
function hex(s,    i, c, v) {
    s = tolower(s); sub(/^0x/, "", s); v = 0
    for (i = 1; i <= length(s); i++) {
        c = index("0123456789abcdef", substr(s, i, 1))
        if (c == 0) return -1
        v = v * 16 + c - 1
    }
    return v
}
BEGIN {
    n = split(breakout, b, ",")
    for (i = 1; i <= n; i++) {
        if (b[i] == "") continue
        c = b[i] + 0
        if (c < 1 || c > 32) die("cage " b[i] " is not 1-32")
        if (c in split4) die("cage " c " is listed twice")
        split4[c] = 1
    }
    l = 1
    for (c = 1; c <= 32; c++) { newlog[c] = l; l += (c in split4) ? 4 : 1 }
}
{
    key = $1; val = $2
    if (!match(key, /_[0-9]+$/)) die("unexpected key " key)
    old = substr(key, RSTART + 1) + 0
    if (!(old in newlog)) die(key " is not one of the 32 cages")
    nk = substr(key, 1, RSTART) newlog[old]
    if (key ~ /^portmap_/) { phys[old] = val + 0; pm[newlog[old]] = val; next }
    if (key ~ /^phy_xaui_(rx|tx)_polarity_flip_/) {
        pol[nk] = val
        if (old in split4) {
            m = hex(val); if (m < 0) die("bad polarity " key "=" val)
            dir = (key ~ /_rx_/) ? "rx" : "tx"
            for (i = 1; i < 4; i++)
                sub4[sprintf("phy_xaui_%s_polarity_flip_%d", dir, newlog[old] + i)] = \
                    sprintf("0x%x", int(m / 2 ^ i) % 2)
        }
        next
    }
    if (key ~ /^xgxs_/) { pol[nk] = val; next }
    ser[nk] = val
}
END {
    if (bad) exit 1
    # The Trident II takes at most 52 front-panel ports per pipeline, and
    # the pipelines split the physical lanes at 64.
    for (c = 1; c <= 32; c++) {
        w = (c in split4) ? 4 : 1
        if (phys[c] <= 64) px += w; else py += w
        nports += w
    }
    if (px > 52 || py > 52)
        die(sprintf("%d and %d ports on the two pipelines; the Trident II takes 52 each", px, py))
    if (nports > 64)
        die(nports " interfaces; NOSaic builds at most 64 (NOSAIC_MAX_TAPS)")

    f = out "/portmap.conf"
    print hdr > f
    print "# Layout: " (breakout == "" ? "32x40G" : "cages " breakout " as 4x10G") > f
    for (c = 1; c <= 32; c++) print "portmap_" newlog[c] "=" pm[newlog[c]] > f
    print "" > f
    print "# Interfaces: et<cage>, or et<cage>_<lane> when broken out." > f
    for (c = 1; c <= 32; c++) {
        L = newlog[c]
        if (c in split4)
            for (i = 0; i < 4; i++)
                printf "tap_et%d_%d=%d:%d:1500\n", c, i + 1, L + i, 1000 + L + i > f
        else
            printf "tap_et%d=%d:%d:1500\n", c, L, 1000 + L > f
    }

    f = out "/polarity.conf"
    print hdr > f
    for (k in pol) print k "=" pol[k] | "sort >> " out "/polarity.conf"
    close("sort >> " out "/polarity.conf")
    if (length(sub4) > 0) {
        print "# Lanes 2-4 of broken-out cages: one bit of the cage mask each." >> f
        for (k in sub4) print k "=" sub4[k] | "sort >> " out "/polarity.conf"
        close("sort >> " out "/polarity.conf")
    }

    f = out "/serdes.conf"
    print hdr > f
    for (k in ser) print k "=" ser[k] | "sort >> " out "/serdes.conf"
    close("sort >> " out "/serdes.conf")

    f = out "/portmode.conf"
    print hdr > f
    for (c = 1; c <= 32; c++)
        if (c in split4) print "nosaic_portmode_" newlog[c] "=4x10g" > f

    printf "wrote %s: %d cages, %d ports (%d/%d per pipeline), %d interfaces\n", \
        out, 32, nports, px, py, nports > "/dev/stderr"
}' || { rm -f "$OUT"/.*.tmp "$OUT/portmap.conf" "$OUT/polarity.conf" "$OUT/serdes.conf" "$OUT/portmode.conf"
        echo "error: refused; nothing written" >&2; exit 1; }
rm -f "$OUT/.portmap.tmp" "$OUT/.polarity.tmp" "$OUT/.serdes.tmp"
