#!/bin/sh
# Generate this board's LED processor program from SONiC's led_proc_init.soc.
#
# WHY THIS EXISTS
#
# The S6000's port LEDs are driven by the Trident II's own two LED processors,
# not by a board controller. They run a small program Dell wrote (132 bytes)
# with a table that maps each LED slot to a port. SONiC loads it with
# `bcmcmd rcload led_proc_init.soc` after the chip is up; NOSaic's datapath
# loads it from ledproc.conf (datapath/td2/ledproc.c). The program and the map
# are Dell's, so NOSaic ships this generator and not its output.
#
# Any S6000's file will do -- it describes the board, not the unit:
#   - on a switch running SONiC: /usr/share/sonic/device/x86_64-dell_s6000_s1220-r0/led_proc_init.soc
#   - from sonic-buildimage: device/dell/x86_64-dell_s6000_s1220-r0/led_proc_init.soc
#
# WHAT IT UNDERSTANDS, AND ONLY THAT
#
#   led <0|1> stop|start|auto on|off|prog <hex...>
#   modreg CMIC_LEDUP<0|1>_PORT_ORDER_REMAP_<lo>_<hi> REMAP_PORT_<n>=<v> ...
#
# Anything else is refused and nothing is written: a .soc that does more than
# this does something ledproc.c would silently not do.
#
# The program is split into 32-byte keys because the datapath's config reader
# takes lines up to 512 bytes, and a 256-byte program in hex on one line would
# be cut and its tail dropped without a word.
#
# USAGE
#   ./mkledproc.sh <led_proc_init.soc> <output-dir>    -> <output-dir>/ledproc.conf
#
# then, like mkconf.sh's output, into /mnt/data/config on an installed switch
# or platform/dell-s6000-on/config/ before `make image`/`make netboot`. Never
# commit it.
set -eu
[ $# -eq 2 ] || { echo "usage: $0 <led_proc_init.soc> <output-dir>" >&2; exit 2; }
IN=$1; OUT=$2
[ -r "$IN" ] || { echo "error: cannot read $IN" >&2; exit 1; }
mkdir -p "$OUT"
awk '
function hex(s,  i, c, v) { s = tolower(s); sub(/^0x/, "", s); v = 0
    for (i = 1; i <= length(s); i++) { c = index("0123456789abcdef", substr(s, i, 1))
        if (c == 0) return -1; v = v * 16 + c - 1 }
    return v }
function num(s) { return s ~ /^0[xX][0-9a-fA-F]+$/ ? hex(s) : (s ~ /^[0-9]+$/ ? s + 0 : -1) }
function die(m) { printf "error: line %d: %s\n", NR, m > "/dev/stderr"; bad = 1; exit 1 }
{ sub(/#.*/, "") }
NF == 0 { next }
$1 == "led" && $2 ~ /^[01]$/ {
    u = $2
    if ($3 == "stop") next
    if ($3 == "start") { start[u] = 1; next }
    if ($3 == "auto") { auto[u] = ($4 == "off") ? 0 : 1; next }
    if ($3 == "prog") { p = ""; for (i = 4; i <= NF; i++) p = p $i; p = toupper(p)
        if (p !~ /^[0-9A-F]+$/ || length(p) % 2) die("bad program hex")
        if (length(p) / 2 > 256) die("program longer than 256 bytes")
        prog[u] = p; next }
    die("unsupported led command: " $3)
}
$1 == "modreg" && $2 ~ /^CMIC_LEDUP[01]_PORT_ORDER_REMAP_[0-9]+_[0-9]+$/ {
    u = substr($2, 11, 1); split($2, r, "_"); lo = r[6] + 0; hi = r[7] + 0
    for (i = 3; i <= NF; i++) { split($i, kv, "=")
        if (kv[1] !~ /^REMAP_PORT_[0-9]+$/) die("unknown field " kv[1])
        s = substr(kv[1], 12) + 0; v = num(kv[2])
        if (s < lo || s > hi) die(kv[1] " is not a field of " $2)
        if (v < 0 || v > 63) die("remap value out of range: " $i)
        remap[u, s] = v; has[u, s] = 1 }
    next }
{ die("unsupported command: " $0) }
END { if (bad) exit 1
    for (u = 0; u < 2; u++) { if (!(u in prog)) continue
        printf "ledproc_%d_prog_len=%d\n", u, length(prog[u]) / 2
        for (o = 0; o * 2 < length(prog[u]); o += 32)
            printf "ledproc_%d_prog_%d=%s\n", u, o, substr(prog[u], o * 2 + 1, 64)
        for (s = 0; s < 64; s++) if ((u, s) in has) printf "ledproc_%d_remap_%d=%d\n", u, s, remap[u, s]
        printf "ledproc_%d_auto=%d\nledproc_%d_start=%d\n", u, (u in auto) ? auto[u] : 0, u, (u in start) ? 1 : 0 }
}' "$IN" > "$OUT/.ledproc.tmp" || { rm -f "$OUT/.ledproc.tmp"; echo "error: refused; nothing written" >&2; exit 1; }
{ printf '%s\n' "# Generated by platform/dell-s6000-on/tools/mkledproc.sh from" \
    "#   $(basename "$IN")" "# Vendor-derived LED processor program. Do not commit."
  cat "$OUT/.ledproc.tmp"; } > "$OUT/ledproc.conf"
rm -f "$OUT/.ledproc.tmp"
echo "wrote $OUT/ledproc.conf ($(grep -c '^ledproc_' "$OUT/ledproc.conf") keys)" >&2
