package imgbuild

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// initScript is the first userspace the machine runs.
//
// Its whole job is to get from "the kernel has started" to "the real root is
// mounted and init is running". It selects an A/B slot, mounts that image
// read-only, puts the slot's persistent writable layer over it, and hands over.
//
// It is deliberately small and deliberately loud. An initramfs that fails
// silently leaves a machine that appears hung with no explanation, and on a
// switch in a rack the console is often the only diagnostic there is.
const initScript = `#!/bin/sh
# Generated by nosaic. The initramfs: pick a slot, mount it, overlay it, hand over.

fail() {
    echo
    echo "NOSAIC-INITRAMFS-FAIL $*"
    echo "dropping to a shell; the image was not mounted"
    exec /bin/sh
}

/bin/busybox --install -s /bin 2>/dev/null

mkdir -p /proc /sys /dev /mnt/image /mnt/data /mnt/root
mount -t proc     proc     /proc  || fail "cannot mount /proc"
mount -t sysfs    sysfs    /sys   || fail "cannot mount /sys"
mount -t devtmpfs devtmpfs /dev   || fail "cannot mount /dev"

echo "NOSAIC-INITRAMFS starting"

# A rootfs carried inside the initramfs, for booting with no NOSaic partitions
# at all. That is how a switch is tried before anything is written to it:
# Aboot's "boot --testonly <url>" fetches the image over the network into RAM,
# so the flash still holds the vendor's layout and there is no slot to find.
#
# Checked before anything probes storage. Doing it afterwards still worked, but
# printed two warnings about missing partitions first -- on a boot where their
# absence is the entire intention. Warnings that are expected teach an operator
# to ignore warnings.
if [ -f /nosaic-rootfs.sqsh ]; then
    echo "NOSAIC-INITRAMFS booting from RAM, no partitions used"
    # The image is moved onto its own tmpfs before it is mounted, and that is
    # not tidiness.
    #
    # switch_root deletes the initramfs to free the memory it occupies, and it
    # deletes whatever is still sitting in it -- including the file a loop
    # device is reading the root filesystem out of. The loop device keeps the
    # inode alive so this mostly works, and mostly is the problem: a 125 MB
    # binary read back with pages of zeros in the middle of it, deterministic
    # enough to crash in the same place and transient enough that dropping
    # caches and reading again returned the correct bytes. What that looks like
    # from userspace is a jump into a zero page, reported as an illegal
    # instruction -- which on a soft-float e500v2 reads as the toolchain fault
    # this architecture is expected to produce, and is not one.
    #
    # A separate tmpfs is a separate filesystem, and switch_root does not
    # descend into those. The file stays where the loop device left it.
    mount -t tmpfs tmpfs /mnt/rootsrc 2>/dev/null \
        || fail "no tmpfs for the embedded rootfs"
    mv /nosaic-rootfs.sqsh /mnt/rootsrc/ \
        || fail "cannot move the embedded rootfs onto its own tmpfs"
    mount -t squashfs -o ro,loop /mnt/rootsrc/nosaic-rootfs.sqsh /mnt/image \
        || fail "the embedded rootfs will not mount"
    echo "NOSAIC-INITRAMFS image mounted"
    echo "NOSAIC-BOOT-SLOT ram"
    mount -t tmpfs tmpfs /mnt/data 2>/dev/null || true
    mkdir -p /mnt/data/slot-ram/upper/etc/nosaic /mnt/data/slot-ram/work
    # The generated per-switch configuration lives here on a real install. It
    # is created on a RAM boot too so the path is the same either way -- an
    # operator should not have to know which kind of boot this is to know where
    # a port map goes. Nothing here survives the reboot, and that is what
    # stateless means.
    mkdir -p /mnt/data/config
    # ...and filled from flash if this board keeps any there.
    #
    # A RAM boot has no persistent slot, so without this every switch comes up
    # with only the configuration built into its image -- which means changing
    # an address means building an image. The flash partition survives both a
    # reboot and an image replacement, so a nosaic/config directory on it is
    # the one place a switch's own settings can live.
    #
    # Discovered by looking rather than declared: the partition that holds the
    # configuration is the one with the configuration on it. Every step is
    # allowed to fail -- a board with no such partition, or a partition with no
    # such directory, is the normal case and must still boot.
    for _d in /dev/mmcblk0p1 /dev/sda1 /dev/vda1 /dev/mmcblk0p2; do
        [ -b "$_d" ] || continue
        mkdir -p /mnt/flash
        mount -t vfat -o ro "$_d" /mnt/flash 2>/dev/null || continue
        if [ -d /mnt/flash/nosaic/config ]; then
            cp -a /mnt/flash/nosaic/config/. /mnt/data/config/ 2>/dev/null \
                && echo "NOSAIC-INITRAMFS site configuration from $_d"
            umount /mnt/flash 2>/dev/null || true
            break
        fi
        umount /mnt/flash 2>/dev/null || true
    done
    # Tells the booted system it has no persistence by design, so its self-test
    # does not report the absence as a fault.
    : > /mnt/data/slot-ram/upper/etc/nosaic/ramboot
    mount -t overlay overlay \
        -o lowerdir=/mnt/image,upperdir=/mnt/data/slot-ram/upper,workdir=/mnt/data/slot-ram/work \
        /mnt/root || fail "cannot assemble the overlay"
    echo "NOSAIC-INITRAMFS overlay assembled (persistent=no)"
    [ -x /mnt/root/sbin/init ] || fail "the image has no /sbin/init"

    # Carry the data mount and /dev across, exactly as the disk path does.
    #
    # Without this the running system has no /mnt/data at all: it is mounted
    # here, used to build the overlay, and then left behind by switch_root.
    # Everything that looks for per-switch configuration there finds nothing,
    # and the failure is silent -- the directory is simply absent, which reads
    # as "nothing has been configured" rather than as a boot path that dropped
    # it. On a RAM boot the contents do not survive a reboot, but the PATH must
    # be the same either way or nothing can be written to work on both.
    mkdir -p /mnt/root/mnt/data
    mount --move /mnt/data /mnt/root/mnt/data 2>/dev/null
    mount --move /dev /mnt/root/dev 2>/dev/null

    echo "NOSAIC-BOOT userspace reached (ram)"
    echo "NOSAIC-INITRAMFS handing over to /sbin/init"
    exec switch_root /mnt/root /sbin/init || fail "switch_root failed"
fi

# The persistent partition comes first, because the slot decision is recorded
# there. A switch that cannot read it still boots: it falls back to slot A
# stateless rather than sitting in an initramfs shell in a rack somewhere.
# The slot pointer, on its own journal-less filesystem. Read before anything
# else, because it decides what gets mounted.
# Some boards have no partition of ours to use, and cannot be given one. The
# bootloader owns the only filesystem on the disk -- Aboot's FAT on an Arista,
# fully allocated, where making room would mean cutting into the vendor image
# that is the box's way back. There the slots and the persistent partition are
# files on that filesystem, loop-mounted.
#
# This is the vendor's own boot path on such a board rather than a workaround
# for it: EOS loop-mounts its root filesystem out of a file on this same FAT,
# and has since 2017. Where we differ is deliberate -- EOS keeps its writable
# layer in tmpfs, and ours has to be an ext4 image, because a per-slot overlay
# that does not survive a reboot makes a rollback meaningless.
FLASH=""
mount_flash() {
    [ -n "$FLASH" ] && return 0
    # Already mounted, by an earlier call in a subshell.
    #
    # slotdev() is invoked as "$(slotdev ...)", so a mount it makes persists in
    # the namespace while the FLASH it assigned is discarded with the subshell.
    # Without this check the second call -- which is the rollback path -- tried
    # to mount an already-mounted device, failed, and reported no slot file on
    # a board whose slot file was sitting right there.
    if grep -q " /mnt/flash " /proc/mounts 2>/dev/null; then
        FLASH=/mnt/flash
        return 0
    fi
    # ⚠ WAIT FOR THE DEVICE. IT MAY NOT EXIST YET.
    #
    # On a board whose flash is eMMC or virtio the node is there before /init
    # runs, because the kernel enumerates those synchronously. On one whose
    # flash is a USB stick -- which is what an Arista 7050TX-64 has -- it is
    # not: the USB stack finds the device a second or two later, and probing
    # once finds nothing.
    #
    # The failure is not a message about storage. Every candidate is skipped,
    # no slot file is found, and the boot stops at "unknown slot 'a'" with the
    # disk arriving in the log immediately afterwards. That reads as a bad
    # image or a bad slot, and it is neither.
    #
    # Bounded, and it costs nothing where the device is already present: the
    # first pass returns immediately on such a board, and only a board with no
    # usable flash at all waits out the timeout -- which is a boot that is
    # going to fail regardless, and is better for having said so slowly.
    _waited=0
    while :; do
        for _d in /dev/mmcblk0p1 /dev/sda1 /dev/vda1; do
            [ -b "$_d" ] || continue
            mkdir -p /mnt/flash
            mount -t vfat "$_d" /mnt/flash 2>/dev/null || continue
            FLASH=/mnt/flash
            # ⚠ NOT STDOUT. This function is called from inside slotdev(),
            # whose stdout IS its return value, so anything printed here is
            # captured as the slot's device path. A board with no flash
            # filesystem then tries to mount a warning message as squashfs and
            # fails with "slot a does not contain a mountable image", which
            # names the slot and says nothing about the real cause.
            [ "$_waited" -gt 0 ] && \
                echo "NOSAIC-INITRAMFS flash appeared after ${_waited}s ($_d)" >&2
            return 0
        done
        # A board whose state is already on a real partition does not have
        # its slots in files on a bootloader filesystem, so there is nothing
        # to wait for: waiting adds the timeout to every boot of every
        # partitioned board to no purpose.
        [ "${FLASH_OPTIONAL:-no}" = yes ] && break
        [ "$_waited" -ge 15 ] && break
        _waited=$((_waited + 1))
        sleep 1
    done
    [ "${FLASH_OPTIONAL:-no}" = yes ] || \
        echo "NOSAIC-INITRAMFS-WARN no flash filesystem after ${_waited}s" >&2
    return 1
}

PERSIST=no
DATA="$(findfs LABEL=nosaic-data 2>/dev/null || echo /dev/vda4)"
if mount -t ext4 "$DATA" /mnt/data 2>/dev/null; then
    echo "NOSAIC-INITRAMFS data partition mounted ($DATA)"
    # This board keeps its state in partitions, so its slots are partitions
    # too and no bootloader filesystem needs waiting for.
    FLASH_OPTIONAL=yes
    mkdir -p /mnt/data/config /mnt/data/secrets
    PERSIST=yes
elif mount_flash && [ -f "$FLASH/nosaic-data.img" ] \
     && mount -o loop "$FLASH/nosaic-data.img" /mnt/data 2>/dev/null; then
    echo "NOSAIC-INITRAMFS data image mounted ($FLASH/nosaic-data.img)"
    mkdir -p /mnt/data/config /mnt/data/secrets
    PERSIST=yes
else
    echo "NOSAIC-INITRAMFS-WARN no data partition; booting stateless"
    mount -t tmpfs tmpfs /mnt/data || fail "cannot mount a fallback writable layer"
fi

# A record of what this boot decided, where it can be read afterwards.
#
# Everything below prints to the console, and a switch in a rack does not have
# one attached. A trial boot that rolls back leaves no other trace: the slot
# files are cleaned up as part of rolling back, so by the time anyone looks, the
# evidence of why is gone. Appending to the data partition costs nothing and is
# the difference between "the trial failed" and knowing which step failed.
blog() {
    echo "$@"
    [ "$PERSIST" = yes ] && printf '%s %s\n' "$(cat /proc/uptime 2>/dev/null | cut -d. -f1)s" "$*" \
        >> /mnt/data/boot/log 2>/dev/null || true
}

mkdir -p /mnt/boot

# ⚠ THE LABEL IS LOOKED FOR IN BOTH CASES, BECAUSE FAT HAS NO LOWERCASE.
#
# On a board whose firmware is its own bootloader this partition is the EFI
# system partition, so it is FAT -- and a FAT label is stored uppercase
# whatever was asked for. findfs compares exactly, so LABEL=nosaic-boot
# matches the ext2 boards and misses the UEFI ones, which then fall through to
# the /dev/vda1 guess and boot slot A stateless for ever: A/B keeps appearing
# to work and no upgrade is ever reversible.
#
# PARTLABEL is tried after both, for a disk whose filesystem label was lost but
# whose GPT names survive.
BOOTDEV="$(findfs LABEL=nosaic-boot 2>/dev/null \
        || findfs LABEL=NOSAIC-BOOT 2>/dev/null \
        || findfs PARTLABEL=nosaic-boot 2>/dev/null \
        || echo /dev/vda1)"

# ext2 first, then vfat. Tried rather than derived: the initramfs is one script
# for every board and it does not know which kind of boot partition this disk
# has, and letting mount name the wrong type first costs nothing.
if mount -t ext2 "$BOOTDEV" /mnt/boot 2>/dev/null \
   || mount -t vfat "$BOOTDEV" /mnt/boot 2>/dev/null; then
    B=/mnt/boot/boot
    mkdir -p $B
elif [ "$PERSIST" = yes ]; then
    # No boot partition, but a persistent one exists.
    #
    # A DOS partition table has only four primaries, and a board whose firmware
    # reads the FIT out of a raw partition needs one of them for that -- so
    # such a board has no separate boot filesystem. Putting the slot pointer on
    # the data partition keeps A/B working there: what matters is that the
    # choice survives a reboot, not which filesystem records it. Falling
    # through to /tmp would silently make every upgrade non-reversible, because
    # a trial that cannot record its attempt can never be rolled back.
    B=/mnt/data/boot
    mkdir -p $B
    echo "NOSAIC-INITRAMFS slot state on the data partition"
else
    echo "NOSAIC-INITRAMFS-WARN no boot partition; defaulting to slot a"
    B=/tmp/boot
    mkdir -p $B
fi

# Slots are found by label first. The device names below are a fallback for a
# disk that has our partitions but no readable labels, and they are guesses:
# virtio on a VM, SCSI/SATA on most switches, eMMC on some. Naming one disk
# would have been wrong on every board that is not that disk.
slotdev() {
    local want=""
    case "$1" in
        a) want=nosaic-slot-a ;;
        b) want=nosaic-slot-b ;;
        *) echo ""; return ;;
    esac
    findfs "LABEL=$want" 2>/dev/null && return

    # The GPT partition name, read from the kernel rather than from findfs.
    #
    # A squashfs has no filesystem label, so the line above never finds a
    # slot; on a disk NOSaic owns outright the numeric guess below lands on
    # the right partition anyway. On an ONIE x86 box it does not: ONIE's
    # GRUB-BOOT and ONIE-BOOT come first, and "partition 2" is ONIE. The
    # kernel publishes every GPT name as PARTNAME in the partition's uevent,
    # which needs nothing from busybox.
    for _u in /sys/class/block/*/uevent; do
        grep -qx "PARTNAME=$want" "$_u" 2>/dev/null || continue
        _n=$(sed -n 's/^DEVNAME=//p' "$_u")
        [ -b "/dev/$_n" ] && { echo "/dev/$_n"; return; }
    done

    # A slot file on the bootloader's own filesystem, for boards where the
    # bootloader owns the whole disk and there is no room for a partition of
    # ours. Returned as a path rather than a device; mount_image() loop-mounts
    # whichever kind it is handed, so the A/B logic above never learns which
    # sort of board it is running on.
    #
    # This is tried BEFORE the numeric guess below, and the order is the whole
    # point. On an Arista, /dev/mmcblk0p2 exists and is the vendor's 1 MB
    # diagnostics partition -- so the guess succeeded, returned a device that
    # was never ours, and the boot failed one step later trying to mount it as
    # squashfs. A guess that lands on a real device belonging to someone else
    # is worse than one that finds nothing.
    if mount_flash && [ -f "$FLASH/$want.sqsh" ]; then
        echo "$FLASH/$want.sqsh"
        return
    fi

    # The data filesystem, as a fallback and with a warning.
    #
    # This is NOT where a slot belongs -- the bootloader cannot read it, and
    # the per-slot overlays it does hold have to share the space. It is checked
    # because an installer that put a slot here once, and a slot file that
    # exists and is silently ignored is the worst of the available outcomes: an
    # upgrade that writes its image, marks its trial, rolls back for want of a
    # file that is right there, and comes up healthy on the old slot with every
    # signal saying it worked.
    if [ -f "/mnt/data/$want.sqsh" ]; then
        echo "NOSAIC-BOOT-WARN slot file found on the data filesystem" \
             "(/mnt/data/$want.sqsh), which is not where the installer should" \
             "put it" >&2
        echo "/mnt/data/$want.sqsh"
        return
    fi

    # The numeric guess, for one of our disks whose labels are unreadable.
    # A device carrying a squashfs is taken in preference to one that merely
    # exists -- but if none of them do, the first that exists is still
    # returned. That fallback is deliberate: a trial slot holding a corrupt
    # image has to reach the mount and fail there, because that is what
    # triggers the rollback. Returning nothing instead would turn a
    # recoverable bad upgrade into a board that will not boot.
    local n="" first=""
    case "$1" in a) n=2 ;; b) n=3 ;; esac
    for d in /dev/vda /dev/sda /dev/mmcblk0p; do
        [ -b "$d$n" ] || continue
        [ -n "$first" ] || first="$d$n"
        if [ "$(dd if="$d$n" bs=4 count=1 2>/dev/null)" = "hsqs" ]; then
            echo "$d$n"
            return
        fi
    done
    echo "$first"
}

# A slot is a partition on most boards and a file on the rest. The only
# difference is the loop device, so it is confined to here.
mount_image() {
    if [ -b "$1" ]; then
        mount -t squashfs -o ro "$1" /mnt/image 2>/dev/null
    else
        mount -t squashfs -o ro,loop "$1" /mnt/image 2>/dev/null
    fi
}

ACTIVE="$(cat $B/active 2>/dev/null || echo a)"
TRIAL="$(cat $B/trial  2>/dev/null || echo '')"
TRIES="$(cat $B/tries  2>/dev/null || echo 0)"
MAXTRIES=3

# A command-line override wins, for recovery and for testing. It is never
# written back, so it cannot accidentally become the committed choice.
for arg in $(cat /proc/cmdline); do
    case "$arg" in nosaic.slot=*) ACTIVE="${arg#nosaic.slot=}"; TRIAL="" ;; esac
done

SLOT="$ACTIVE"
if [ -n "$TRIAL" ]; then
    if [ "$TRIES" -ge "$MAXTRIES" ]; then
        # The trial slot booted but never confirmed itself healthy. An image
        # that starts and then does not work is exactly what rollback is for.
        echo "NOSAIC-BOOT-ROLLBACK slot $TRIAL failed to confirm after $TRIES attempts; returning to $ACTIVE"
        rm -f $B/trial $B/tries
    else
        TRIES=$((TRIES + 1))
        echo "$TRIES" > $B/tries 2>/dev/null
        SLOT="$TRIAL"
        echo "NOSAIC-BOOT-TRIAL slot $TRIAL attempt $TRIES of $MAXTRIES"
    fi
fi

SLOTDEV="$(slotdev "$SLOT")"
blog "NOSAIC-BOOT want slot $SLOT, active=$ACTIVE trial=${TRIAL:-none} tries=$TRIES"
blog "NOSAIC-BOOT slotdev=${SLOTDEV:-NONE} sda2=$([ -b /dev/sda2 ] && echo y || echo n) sda3=$([ -b /dev/sda3 ] && echo y || echo n)"
if [ -z "$SLOTDEV" ] && [ "$SLOT" != "$ACTIVE" ]; then
    # The trial slot cannot be found at all -- no partition, no slot file.
    # That is the same verdict as a trial that will not mount, and it gets the
    # same treatment, because the active slot is still there and still known
    # good. Failing the boot here would turn a bad upgrade into a dark switch.
    blog "NOSAIC-BOOT-ROLLBACK slot $SLOT could not be found; returning to $ACTIVE"
    rm -f $B/trial $B/tries
    SLOT="$ACTIVE"
    SLOTDEV="$(slotdev "$SLOT")"
fi
[ -n "$SLOTDEV" ] || fail "unknown slot '$SLOT'"
echo "NOSAIC-INITRAMFS slot $SLOT ($SLOTDEV)"

if ! mount_image "$SLOTDEV"; then
    # A trial slot that will not even mount is definitively bad. There is
    # nothing to learn from retrying it, so roll back at once rather than
    # spending the trial budget discovering the same thing three times.
    if [ "$SLOT" != "$ACTIVE" ]; then
        blog "NOSAIC-BOOT-ROLLBACK $SLOTDEV would not mount as squashfs; returning to $ACTIVE"
        rm -f $B/trial $B/tries
        SLOT="$ACTIVE"
        SLOTDEV="$(slotdev "$SLOT")"
        mount_image "$SLOTDEV" || fail "slot $ACTIVE is unmountable too; there is nothing left to boot"
    else
        fail "slot $SLOT does not contain a mountable image"
    fi
fi
echo "NOSAIC-INITRAMFS image mounted"
echo "NOSAIC-BOOT-SLOT $SLOT"

UPPER="/mnt/data/slot-$SLOT/upper"
WORK="/mnt/data/slot-$SLOT/work"
mkdir -p "$UPPER" "$WORK"

mount -t overlay overlay \
    -o lowerdir=/mnt/image,upperdir=$UPPER,workdir=$WORK \
    /mnt/root || fail "cannot assemble the overlay"
echo "NOSAIC-INITRAMFS overlay assembled (persistent=$PERSIST)"

[ -x /mnt/root/sbin/init ] || fail "the image has no /sbin/init"

# Carry the data partition and the pseudo-filesystems into the real root, so
# the running system does not have to re-mount what is already mounted.
mkdir -p /mnt/root/mnt/data /mnt/root/mnt/boot /mnt/root/mnt/flash
mount --move /mnt/data /mnt/root/mnt/data 2>/dev/null
mount --move /mnt/boot /mnt/root/mnt/boot 2>/dev/null
# The bootloader's filesystem, on a board whose slots are files on it. Carried
# so the running system can address its own slots: without it every install
# starts by hand-mounting the flash, which is precisely the step that gets
# forgotten. Absent on a partitioned board, where this does nothing.
mount --move /mnt/flash /mnt/root/mnt/flash 2>/dev/null
mount --move /dev /mnt/root/dev 2>/dev/null

echo "NOSAIC-INITRAMFS handing over to /sbin/init"
exec switch_root /mnt/root /sbin/init || fail "switch_root failed"
`

// buildInitramfs packs a busybox and the init script above into a cpio.
//
// busybox comes from the composed image rather than from a separate build, so
// the initramfs and the system it boots are the same binary — which is why
// that package is built static.
// buildInitramfs packs busybox, the init script, and — when embed is non-empty
// — the root filesystem itself.
//
// Embedding makes the image self-contained: kernel plus initramfs and nothing
// else, which is what a switch needs to be tried before anything is written to
// it. Aboot fetches such an image over the network and runs it from RAM, so
// there are no NOSaic partitions to find and the vendor's OS is still intact
// on flash.
//
// It is not the normal shape. An installed switch mounts its slot from flash;
// this exists so the first boot on a new board risks nothing.
func buildInitramfs(o Options, work, rootfs string, embed string) (string, error) {
	fmt.Fprintf(o.Log, "==> building the initramfs\n")
	dir := filepath.Join(work, "initramfs")
	for _, d := range []string{"bin", "sbin", "proc", "sys", "dev", "mnt", "mnt/rootsrc"} {
		if err := os.MkdirAll(filepath.Join(dir, d), 0o755); err != nil {
			return "", err
		}
	}

	bb := filepath.Join(rootfs, "bin", "busybox")
	if _, err := os.Stat(bb); err != nil {
		return "", fmt.Errorf("the image has no /bin/busybox, so no initramfs can be built: %w", err)
	}
	if err := copyFile(bb, filepath.Join(dir, "bin", "busybox")); err != nil {
		return "", err
	}
	if err := os.Chmod(filepath.Join(dir, "bin", "busybox"), 0o755); err != nil {
		return "", err
	}
	for _, link := range []string{"sh", "mount", "mkdir", "switch_root", "echo"} {
		_ = os.Symlink("busybox", filepath.Join(dir, "bin", link))
	}
	if err := os.WriteFile(filepath.Join(dir, "init"), []byte(initScript), 0o755); err != nil {
		return "", err
	}

	// The root filesystem, carried inside, when this image is meant to boot
	// without touching storage. Copied rather than linked: the cpio has to
	// contain the bytes.
	if embed != "" {
		if err := copyFile(embed, filepath.Join(dir, "nosaic-rootfs.sqsh")); err != nil {
			return "", fmt.Errorf("embedding the root filesystem: %w", err)
		}
		fmt.Fprintf(o.Log, "    embedding the root filesystem for a RAM boot\n")
	}

	out := filepath.Join(o.OutDir, "initramfs.cpio.gz")
	// Sorted names and gzip -n keep this reproducible, like every other
	// artifact: find's traversal order and a gzip timestamp are exactly the
	// two things that would otherwise differ between builds.
	script := fmt.Sprintf(
		`cd %q && find . | LC_ALL=C sort | cpio -o -H newc --quiet --reproducible | gzip -9 -n > %q`,
		dir, out)
	cmd := exec.Command("sh", "-c", script)
	if b, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("packing the initramfs: %v\n%s", err, b)
	}
	return out, nil
}
