package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/salvaged-silicon/nosaic-switch/internal/svcgen"
)

// s6Init is /sbin/init on an s6 profile.
//
// s6-svscan must be PID 1, so everything that has to happen before supervision
// starts happens here and then execs it. The service database is compiled at
// boot rather than shipped compiled: the source form is what the image
// contains, it is what an operator can read and edit, and compiling takes
// milliseconds.
const s6Init = `#!/bin/sh
# Generated by nosaic. /sbin/init for the s6 profile.

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Not silenced. An earlier version sent these to /dev/null, and a /proc that
# failed to mount produced no message at all -- the first sign of it was a
# self-test three steps later complaining it could not read /proc/cmdline.
# Nothing during boot gets to fail quietly.
for m in "proc proc /proc" "sysfs sysfs /sys" "devtmpfs devtmpfs /dev"; do
    set -- $m
    # Already-mounted is not a failure: the initramfs moves /dev across rather
    # than leaving it behind, so warning about it would send somebody looking
    # for a fault that is actually correct behaviour.
    if mountpoint -q "$3" 2>/dev/null; then
        continue
    fi
    if ! mount -t "$1" "$2" "$3" ; then
        echo "NOSAIC-S6-WARN could not mount $3"
    fi
done
mkdir -p /dev/pts /run /tmp
mount -t devpts devpts /dev/pts || echo "NOSAIC-S6-WARN could not mount /dev/pts"
mount -t tmpfs  tmpfs  /run     || echo "NOSAIC-S6-WARN could not mount /run"
hostname nosaic || true

echo "NOSAIC-BOOT userspace reached (s6)"

# Only the scan directory. /run/s6-rc belongs to s6-rc-init, which creates it
# as a symlink to the live directory it builds -- pre-creating it as a
# directory makes that fail with "Is a directory", and compiling the database
# into it makes the collision certain.
mkdir -p /run/service

# Teach PID 1 how to shut down.
#
# s6-svscan takes its signal handling from scripts in the scan directory, and
# with none there a reboot request stops halfway: the supervision tree comes
# down, nothing asks the kernel to restart, and the box sits with its services
# dead and its shell still answering. That is worse than not rebooting at all,
# because it looks like it worked.
#
# These live in /run because the scan directory does, so they are written on
# every boot rather than shipped.
mkdir -p /run/service/.s6-svscan
for sig in TERM INT USR1 USR2; do
    case "$sig" in
        USR1) act=halt     ;;
        USR2) act=poweroff ;;
        *)    act=reboot   ;;
    esac
    printf '#!/bin/sh\nexec /etc/nosaic/shutdown.sh %s\n' "$act" \
        > "/run/service/.s6-svscan/SIG$sig"
    chmod 0755 "/run/service/.s6-svscan/SIG$sig"
done

# Compile the service database that svcgen produced. A failure here is worth
# saying out loud: the system will still supervise whatever is in the scan
# directory, but nothing declared will start, and silence would make that look
# like the services simply did not exist.
# Errors go straight to the console, not into a file to be read back.
#
# The first version captured stderr and cat'd it afterwards, and every failure
# printed nothing at all -- which turned three separate faults into one
# indistinguishable symptom. On a switch the console is the only diagnostic
# there is, so anything that can fail during boot says so where it happens.
s6-rc-compile /run/s6-rc-compiled /etc/s6-rc/source
echo "NOSAIC-S6 compile rc=$?"

# s6-svscan has to be PID 1, so the database is brought up from a child that
# waits for the scan directory to go live.
(
    n=0
    while [ ! -p /run/service/.s6-svscan/control ] && [ $n -lt 60 ]; do
        sleep 1
        n=$((n + 1))
    done
    if [ ! -p /run/service/.s6-svscan/control ]; then
        echo "NOSAIC-S6-FAIL the scan directory never went live after ${n}s"
        rescue=1
    else
        echo "NOSAIC-S6 scan directory live after ${n}s"
        # -t is not optional on a 32-bit board, and the reason is not obvious.
        #
        # Without it s6 uses TAIN_INFINITE_RELATIVE as the deadline, and
        # converting that to a 32-bit time_t overflows -- so the subscribe path
        # fails with EOVERFLOW, which surfaces as "Value too large for defined
        # data type" against whatever file it was working on. It reads like a
        # broken file rather than a deadline that will not fit.
        #
        # Invisible everywhere else: on a 64-bit target skalibs compiles the
        # range check out entirely, and under qemu-user the syscalls land on
        # the host's 64-bit kernel. Only a real 32-bit kernel shows it.
        s6-rc-init -t 30000 -c /run/s6-rc-compiled /run/service
        rc=$?
        echo "NOSAIC-S6 init rc=$rc"
        [ $rc -eq 0 ] || rescue=1
        # Same reason, and it needs its own: s6-rc spawns s6-svlisten, which
        # subscribes the same way and failed identically until given a deadline
        # that fits.
        # The deadline has to exceed the longest a service legitimately spends
        # waiting on hardware, and it did not.
        #
        # network-config waits for the front-panel ports to appear -- up to
        # NOSAIC_NET_WAIT, 600 s by default -- and on an image that does not
        # forward they never do. At 120 s the bundle change gave up, this
        # script read that as the service database failing, and a switch that
        # was merely not forwarding announced NOSAIC-S6-FAIL and dropped an
        # unauthenticated root shell on its console. Observed on a 7050SX2
        # given an image with an empty port map: the box looked catastrophic
        # and was in fact one rollback away from fine.
        #
        # The rescue path is for a database that cannot come up, not for a
        # service that is patiently waiting for silicon.
        #
        # ⚠ AND SILICON CAN BE SLOWER THAN YOU THINK. Eleven minutes was
        # chosen against a board whose datapath is up in one. On the 7050TX-64
        # it is not enough: Broadcom's driver downloads firmware to 48 external
        # PHYs over MDIO before the chip reports its ports -- 1.8 million
        # register writes, about thirteen minutes -- so the transaction expired
        # while network-config was still waiting for the front-panel
        # interfaces. The result is a switch with every other service running,
        # its copper ports linked, and no addressing on any of them, which
        # reads as a dead data plane rather than as a timeout.
        #
        # The ceiling costs nothing on a fast board: the transaction ends when
        # the last service is up, not when the timer expires.
        s6-rc -t 1800000 -u change default
        rc=$?
        echo "NOSAIC-S6 change rc=$rc"
        [ $rc -eq 0 ] || rescue=1
    fi
    /etc/nosaic/selftest.sh

    # If the service database did not come up, nothing started -- including the
    # getty. The box is then reachable only by power-cycling it, which tells you
    # nothing about why. So put a shell on the console instead.
    #
    # Deliberately unauthenticated, and deliberately only on this path: it
    # exists because the alternative is a switch that boots to silence. The
    # supervised getty is what runs when the system is working, and it asks who
    # you are.
    if [ "${rescue:-0}" = 1 ]; then
        echo "NOSAIC-S6-FAIL the service database did not come up"
        echo "NOSAIC-RESCUE shell on the console; the system is NOT running"
        # Enough to diagnose with, gathered before the prompt so it is in the
        # console log even if nobody is watching.
        echo "--- date:"      ; date
        echo "--- mounts:"    ; cat /proc/mounts
        echo "--- servicedirs:" ; ls -la /run/s6-rc/servicedirs 2>&1 | head -20
        echo "--- stat:"      ; busybox stat /run/s6-rc/servicedirs 2>&1 | head -12
        setsid sh -c 'exec sh -i < /dev/console > /dev/console 2>&1' &
    fi
) &

exec s6-svscan /run/service
`

// writeS6 lays down an s6 profile's init and its service database source.
//
// The service directories are generated by svcgen from the same declaration a
// systemd profile would render into a unit. Until this existed that backend
// had never produced files a running system consumed, which meant it was
// tested but not proven.
// bareName strips a systemd-style suffix, since s6 dependency names have none.
func bareName(n string) string {
	for _, suf := range []string{".service", ".target", ".socket"} {
		if strings.HasSuffix(n, suf) {
			return strings.TrimSuffix(n, suf)
		}
	}
	return n
}

func writeS6(o Options, rootfs string, services ...svcgen.Service) error {
	if err := writeFile(rootfs, "/sbin/init", s6Init, 0o755); err != nil {
		return err
	}
	if err := writeFile(rootfs, "/etc/nosaic/shutdown.sh", shutdownScriptFor(o), 0o755); err != nil {
		return err
	}

	backend, err := svcgen.For("s6")
	if err != nil {
		return err
	}

	var names []string
	for _, svc := range services {
		files, err := backend.Generate(svc)
		if err != nil {
			return fmt.Errorf("generating %s: %w", svc.Name, err)
		}
		for _, f := range files {
			if err := writeFile(rootfs, f.Path, f.Content, os.FileMode(f.Mode)); err != nil {
				return err
			}
		}
		names = append(names, svc.Name)
	}

	// Satisfy the well-known ordering names.
	//
	// The two init systems differ here in a way a service declaration should
	// not have to know about: systemd resolves "after: network" against an
	// implicit network.target, while s6-rc requires every dependency to be a
	// real service in the database and refuses to compile otherwise. So the
	// names a declaration may reasonably use are realised here as empty
	// oneshots, which is what such a target is in s6-rc terms.
	//
	// Generated from what the services actually reference rather than from a
	// fixed list, so a new ordering name cannot silently break the compile.
	referenced := map[string]bool{}
	defined := map[string]bool{}
	for _, svc := range services {
		defined[svc.Name] = true
		for _, d := range append(append([]string(nil), svc.After...), svc.Wants...) {
			referenced[bareName(d)] = true
		}
	}
	for name := range referenced {
		if defined[name] {
			continue
		}
		dir := "/etc/s6-rc/source/" + name
		if err := writeFile(rootfs, dir+"/type", "oneshot\n", 0o644); err != nil {
			return err
		}
		if err := writeFile(rootfs, dir+"/up", "/bin/true\n", 0o644); err != nil {
			return err
		}
		names = append(names, name)
	}

	// s6-rc brings up a bundle, not a list, so the generated services need one
	// to belong to. "default" is the name s6-rc-init expects by convention.
	base := "/etc/s6-rc/source/default"
	if err := writeFile(rootfs, base+"/type", "bundle\n", 0o644); err != nil {
		return err
	}
	for _, n := range names {
		if err := writeFile(rootfs, filepath.Join(base, "contents.d", n), "", 0o644); err != nil {
			return err
		}
	}
	return nil
}

// shutdownScript is what PID 1 runs when asked to stop.
//
// Two things it must do that are easy to leave out. It has to bound how long
// it waits for services to stop -- s6-rc will otherwise wait for ever on one
// that does not exit, which is precisely how a reboot turns into a hang. And
// it has to ask the kernel itself rather than signalling init, because init is
// what is running this: signalling it again just arrives back here.
const shutdownScript = `#!/bin/sh
# Generated by nosaic. Run by PID 1 on a shutdown signal.
export PATH=/bin:/sbin:/usr/bin:/usr/sbin

action="${1:-reboot}"
echo "NOSAIC-S6 shutting down for $action"

# Bounded, deliberately. A datapath daemon mid-chip-initialisation can take a
# while to notice, and waiting for ever is how this hangs.
s6-rc -t 15000 -da change 2>&1 || echo "NOSAIC-S6-WARN services did not all stop"

sync

%s
# The kernel directly. -f skips signalling init, which is us.
case "$action" in
    poweroff) exec busybox poweroff -f ;;
    halt)     exec busybox halt -f     ;;
    *)        exec busybox reboot -f   ;;
esac
`

// powerCycleReboot names the platform drivers on whose boards a reboot must
// be a power cycle through the board's own controller.
//
// ⚠ ON THESE BOARDS A CPU RESET IS NOT A REBOOT. The Dell S6000-ON's Trident
// II keeps its state across a warm reset and comes back unusable; Dell's ONIE
// and SONiC both replace reboot with the CPLD write for that reason. The
// kernel reboot below stays as the fallback, so a HAL that cannot reach its
// controller still restarts the box rather than hanging it.
var powerCycleReboot = map[string]bool{"dell-s6000": true}

const powerCycleStep = `if [ "$action" = reboot ]; then
    echo "NOSAIC-S6 rebooting by power cycle through the board controller"
    nosaic platform power-cycle || echo "NOSAIC-S6-WARN power cycle failed; falling back to a CPU reset"
fi
`

func shutdownScriptFor(o Options) string {
	step := ""
	if o.Board != nil && powerCycleReboot[o.Board.PlatformHAL.Driver] {
		step = powerCycleStep
	}
	return fmt.Sprintf(shutdownScript, step)
}
